# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Create symlink for wasm-ld
      run: sudo ln -s $(which wasm-ld-13 || which wasm-ld-12 || which wasm-ld-11 || which wasm-ld-10) /usr/bin/wasm-ld
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@093dfe9d598ec5a42246855d09b49dc76803c005
      with:
        arguments: |
          --build-cache
          build
          -Denterprise.tos.agree=yes
    - name: Run the examples
      uses: gradle/gradle-build-action@093dfe9d598ec5a42246855d09b49dc76803c005
      with:
        arguments: |
          --build-cache
          examples
          -Denterprise.tos.agree=yes
          -Deu.aylett.asmble.processExamples=yes
